const CONFIG = {
    titleWeb: "AnhThuxinhnhat",
    introTitle: 'Wowww, hình như cóa nàng công túa xinh đẹp nào đósinh ngày 19/4 bật web hả taa! ',
    introDesc: `Nhma cô ấy hay tự ôm việc nìa, hong có nghĩ đến sức khỏe nè, đôi khi còn tin người quá mức nựaa, còn nhiều lúc bảo là mình gất hung dữ mà hiền khô để cho ngta ăn hiếp hong lun ó :<`,
    btnIntro: 'hic hic, có hả ',
    title: 'Aizaa, con bé công túa nì toàn làm ngta lo kh àa, nhiều lúc hong bíc làm sao lun.',
    desc: 'Nhma chính vì điều đó lại khiến nàng công túa ấy trở nên xinh đẹp hơn bất cứ ai, cô ấy trở thành phiên bản của riêng cô ấy, điều mà có thể nói là nét đẹp nhất của cô ấy. À mà tự nhiên tui muốn kí đầu con bé công túa ấy ghê :))) ',
    btnYes: 'Tạm tha đó =3',
    btnNo: 'Bn tòyyyy',
    question: 'Ụa sao nay tha cho tui zị, má ưiiii chuyện lạ à nhaaaa',
    btnReply: 'Éc Ô Éc',
    reply: 'tại Anh Thư hứa từ giờ sẽ kh chửi Hưng nựa',
    mess: 'Chời Ưiiiii lạ zị ta',
    messDesc: 'Nhưng mà chúc mừng sinh nhật 20 tủi anhthu nhaa, chúc cho nàng công túa anhthu có cuộc sống bình an, an yên, thẳng thắn mà chân thành, nhiều may mắn và không thị phi. Chúc cho thời gian có thể mãi chầm chậm không vội vàng , chúc cho hạnh phúc có thể mãi không rời bỏ mãi không buông tay. Chúc cho nụ cười của Thu luôn luôn nở trên môi. Và hơn hết chào mừng Ceo qua tuổi 20 đầy nhiệt huyết thanh xuân ',
    btnAccept: 'nhấn ok là qua mess tui nà =3',
    messLink: 'https://www.facebook.com/NgQDinhHung'
